# Generated by Django 6.0.3 on 2026-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
