# Generated by Django 6.0.3 on 2026-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
